# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  RayLibBase_config = debug

else ifeq ($(config),release)
  RayLibBase_config = release

else ifeq ($(config),port)
  RayLibBase_config = port

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := RayLibBase

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

RayLibBase:
ifneq (,$(RayLibBase_config))
	@echo "==== Building RayLibBase ($(RayLibBase_config)) ===="
	@${MAKE} --no-print-directory -C . -f RayLibBase.make config=$(RayLibBase_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f RayLibBase.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  port"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   RayLibBase"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"